### ISSUE TITLE
Error using theme on Project OutFox 0.4.18.1 

### ISSUE THREAD

**Issue by fullStackRacc** [Horsey-/Simply-Love-SM5-1#5]
It seems like it's an issue with all Simply Love themes, but I was hoping because this one seemed to be more Outfox-centric it would still work. 

When I try to use the theme, I just get the "OutFox LTS-0.4.18.1-git-438801a9b6 is not supported by Simply Love error like so: 
![image](https://user-images.githubusercontent.com/106115808/232331815-c1e7f7dc-0a2c-4e3c-9d0b-f6d82ec00157.png)

I'm not sure where it's checking the version, but I am confused because the theme readme specifically says that it is suggested to use that version 

I'll try to dig around and see if I can figure it out, but I figured I would bring it up to see if you had any idea why this was happening

**Comment by fullStackRacc** [comment]
Update: I don't know that it's a *good* solution, but just removing SL-SupportHelpers from the Scripts folder makes it works and kills the lockout. the title screen is missing the logo when I do that, but I don't know if that's something that y'all did intentionally or a side effect

Update: That was a bad idea, *but* just commenting out everything above line 117 fixed the logo and crashing on end screen issues? It seems like it works totally fine if the entire function to check the version is removed. Which like, kind of annoying for potential issue things, but at least that resolved my main issue.

Final update: I am a huge idiot and didn't realize there were actual releases those work fine my bad lmao i just downloaded the latest one

**Comment by Horsey-** [comment]
My understanding about why the version checking doesn't work is because the product version of some OutFox build numbers was prefixed with `LTS-`. The version check in Simply Love derivatives expects a number from ProductVersion(), but since the hardcoded ProductVersion of older builds of OutFox contains the `LTS-` prefix the version check fails. The OutFox devs are aware of this and I'm pretty sure they have moved away from using the problematic prefix and have just fallen back to using product numbers instead. In the future, if you have problems with version checks, the best way to defeat it would be to change the `StepManiaVersionIsSupported` function and comment out the if statements and just have the function return `true`.

**Comment by fullStackRacc** [comment]
Honestly that sounds right, and will likely be what I do if I have any further issues, thank you!

**Comment by Horsey-** [comment]
Rest assured, I try to stay up to date with the latest OutFox build, so if the OutFox version number eventually breaks the version checks in SL-SupportHelpers.lua, I'll either add the new build prefix to the version checks, or just remove the version checks altogether in OutFox. 

My personal philosophy has currently been to use if statements that check for new APIs existing and creating an on-screen error message for the end user instead of straight up crashing the theme or locking out the user. This philosophy may change in the future if there are significant API changes to lock out ITGMania/SM5.1/SM5.0.12 from being feasibly supported. I essentially want the theme to _work_ for as many end users as possible, but utilize onscreen elements to specifically show users what they are missing out on by not moving to OutFox. 

To illustrate the above point, here's what ScreenSelectMusicWide looks like when a user uses this theme in ITGMania
![Screenshot 2023-04-16 at 4 04 55 PM](https://user-images.githubusercontent.com/5679966/232348069-2e83371e-bd07-40f6-9571-db034f243d8b.png)

**Comment by fullStackRacc** [comment]
I think that's a really solid philosophy honestly. Like, at the end of the day the big 3 are still sourced originally from the same base, and i think it's just better to use words to tell users they're missing out on things instead of completely locking them out of using the theme. Still find it weird that Simply Love uses a lockout at all honestly

**Comment by fullStackRacc** [comment]
So, just wanted to give you a heads up, because maybe you have an idea of why this would happen? But I'm trying Release 5.2.1H, and having that function return true worked like a charm, but it crashes on a song fail (and maybe a song win, haven't tried that yet) 

Update: it only seems to crash when the theme is anything other than "Simply Love" (I've had it crash on the pumpkin theme and the arrows on)

**Comment by Horsey-** [comment]
Just DM me with your contact information and we can try having a discord call so I can see exactly what's happening. There are just too many permutations for me to troubleshoot what could be going wrong at a failed evaluation.

**Comment by fullStackRacc** [comment]
It's currently super inconsistent (now it's fine??) i'm just going to do some more testing and I'll email you my info if i can nail down something a little more conclusive. Thank you again for the help and information!

**Comment by Horsey-** [comment]
Now is totally fine. Just DM me your contact info for Discord.
